import Phaser from 'phaser';

// Phaserが内部で持っているEventEmitterを流用して、グローバルなEventBusを作ります
export const GameEventBus = new Phaser.Events.EventEmitter();

export const GAME_EVENTS = {
  PLAYER_MOVE: 'player_move',
  ACTION_BUTTON: 'action_button_pressed',
  INVENTORY_UPDATED: 'inventory_updated',
  CRAFT_REQUEST: 'craft_request',
  CRAFT_SUCCESS: 'craft_success',
  HUNGER_UPDATED: 'hunger_updated',
  TIME_UPDATED: 'time_updated',
  SCORE_UPDATED: 'score_updated',
  PLAYER_DIED: 'player_died',
  GAME_OVER: 'game_over',
  PLAYER_TOOK_DAMAGE: 'player_took_damage',
  HEALTH_UPDATED: 'health_updated',
  GAME_SAVED: 'game_saved',
  GAME_LOADED: 'game_loaded',
  SEASON_CHANGED: 'season_changed',
  GAME_PAUSED: 'game_paused',
  GAME_RESUMED: 'game_resumed',
  SAVE_HOUSE_INTERACT: 'save_house_interact',
  CRAFT_SAVEHOUSE: 'craft_savehouse',
  // 6軸ステータス
  HYDRATION_UPDATED: 'hydration_updated',
  TEMPERATURE_UPDATED: 'temperature_updated',
  SLEEP_UPDATED: 'sleep_updated',
  MENTAL_HEALTH_UPDATED: 'mental_health_updated',
  // 状態異常
  STATUS_EFFECT_CHANGED: 'status_effect_changed',
  // 天候
  WEATHER_CHANGED: 'weather_changed',
  // クラフト追加
  CRAFT_RAFT: 'craft_raft',
  CRAFT_BANDAGE: 'craft_bandage',
  CRAFT_HERB_MEDICINE: 'craft_herb_medicine',
  COOK_MEAT: 'cook_meat',
  // ゲームクリア
  GAME_WIN: 'game_win',
  // 動物・生態系
  ANIMAL_KILLED: 'animal_killed',
  RABBIT_COUNT_CHANGED: 'rabbit_count_changed',
  // 廃村
  LOOT_FOUND: 'loot_found',
  // アクション
  PLAYER_ATTACK: 'player_attack',
  PLAYER_DODGE: 'player_dodge',
  STAMINA_UPDATED: 'stamina_updated',
  // 潮汐
  TIDE_CHANGED: 'tide_changed',
  // SOS
  GENERATOR_REPAIRED: 'generator_repaired',
  NOTIFICATION: 'notification',
  // 技術ツリー
  TECH_LEVEL_UP: 'tech_level_up',
  // 武器
  WEAPON_CHANGED: 'weapon_changed',
  ARROW_FIRED: 'arrow_fired',
  // 道具条件
  TOOL_CONDITION_CHANGED: 'tool_condition_changed',
  // 修理
  REPAIR_TOOL: 'repair_tool',
  // 建設物
  CRAFT_WORKBENCH: 'craft_workbench',
  CRAFT_SPEAR: 'craft_spear',
  CRAFT_ARROW: 'craft_arrow',
  // シェルター
  SHELTER_DAMAGED: 'shelter_damaged',
  SHELTER_REPAIRED: 'shelter_repaired',
  // 経験値・レベル
  XP_GAINED: 'xp_gained',
  LEVEL_UP: 'level_up',
  SKILL_UPDATED: 'skill_updated',
  // 農場
  FARM_PLACED: 'farm_placed',
  FARM_HARVESTED: 'farm_harvested',
  SETTLEMENT_PROGRESS: 'settlement_progress',
  // 定住END
  CRAFT_FARM_PLOT: 'craft_farm_plot',
  // 栄養素
  NUTRITION_UPDATED: 'nutrition_updated',
  CRAMPS_TRIGGERED: 'cramps_triggered',
  // 風
  WIND_CHANGED: 'wind_changed',
  // 精神衛生エフェクト
  MENTAL_EFFECT: 'mental_effect',
  // 水道
  WATER_PUMP_ACTIVE: 'water_pump_active',
  // 釣り
  FISHING_START: 'fishing_start',
  FISH_CAUGHT: 'fish_caught',
  // クラフト追加
  CRAFT_STONE_KNIFE: 'craft_stone_knife',
  CRAFT_STONE_AXE: 'craft_stone_axe',
  CRAFT_FISHING_ROD: 'craft_fishing_rod',
  CRAFT_TRAP: 'craft_trap',
  CRAFT_WARM_CLOTHING: 'craft_warm_clothing',
  COOK_FISH: 'cook_fish',
};